name: architect-workbench
title: architect-workbench
org: Derrick Ampy
author: Derrick Ampy
author_url: https://github.com/dsampy
base_url: ''
ctx_path: ''
interpolate: false 
haml:
  :ugly: true
asciidoctor:
  :safe: safe
  :attributes:
    sitename: architect-workbench
    base_url: ''
    ctx_path: ''
    idprefix: ''
    idseparator: '-'
    sectanchors: ''
    icons: font
